services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 10

  es-init:
    image: curlimages/curl:8.2.1
    depends_on:
      - elasticsearch
    volumes:
      - ./sample_data:/sample_data
      - ./es-init.sh:/es-init.sh
    entrypoint: ["sh", "/es-init.sh"]

  productcatalogapi:
    depends_on:
      elasticsearch:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: productcatalogapi
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 5
